version: '2.24.6'

services:
  app:
    container_name: app
    build: .
  db:
    container_name: db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres:15.4
